name:                cutav
version:             0.1.0.0
github:              "ivxvm/cutav"
license:             BSD3
author:              "Andrii Polishchuk"
maintainer:          "ivxvm@protonmail.com"
copyright:           "2020 Andrii Polishchuk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ivxvm/cutav#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - filepath
  - regex-tdfa
  - free
  default-extensions:
  - DeriveFunctor
  - RecordWildCards
  - MultiWayIf

executables:
  cutav-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cutav
    - optparse-applicative
    default-extensions:
    - StrictData
    - ApplicativeDo
    - RecordWildCards

tests:
  cutav-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cutav
